# Generated by Django 6.0.5 on 2026-06-15 15:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('ruc', models.CharField(help_text='Ejemplo: J0310000123456', max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(14)])),
                ('verified', models.BooleanField(default=False, help_text='✓ Sello Oficial de Verificación')),
                ('city', models.CharField(choices=[('managua', 'Managua'), ('masaya', 'Masaya'), ('esteli', 'Estelí'), ('leon', 'León'), ('granada', 'Granada'), ('jinotega', 'Jinotega'), ('matagalpa', 'Matagalpa'), ('otra', 'Otra')], max_length=50)),
                ('sector', models.CharField(choices=[('alimentos', 'Alimentos'), ('agropecuario', 'Agropecuario'), ('artesanias', 'Artesanías'), ('tecnologia', 'Tecnología'), ('textil', 'Textil'), ('servicios', 'Servicios'), ('otros', 'Otros')], max_length=50)),
                ('popularity_score', models.IntegerField(default=0)),
                ('followers_count', models.IntegerField(default=0)),
                ('associates_count', models.IntegerField(default=0)),
                ('collaborations_count', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-popularity_score'],
            },
        ),
    ]
