# Generated by Django 6.0.5 on 2026-08-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_report_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL externa del logo (ej. Unsplash)', null=True),
        ),
    ]
