# Generated by Django 6.0.5 on 2026-07-27 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('feria', 'Feria'), ('taller', 'Taller'), ('conferencia', 'Conferencia'), ('networking', 'Networking'), ('otro', 'Otro')], default='feria', max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=300)),
                ('city', models.CharField(choices=[('managua', 'Managua'), ('masaya', 'Masaya'), ('esteli', 'Estelí'), ('leon', 'León'), ('granada', 'Granada'), ('jinotega', 'Jinotega'), ('matagalpa', 'Matagalpa'), ('otra', 'Otra')], default='managua', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attending_events', to='users.profile')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='users.profile')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
