# Generated by Django 6.0.5 on 2026-06-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('grok', 'Grok/xAI')], default='gemini', max_length=20),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='tokens_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='korvaaiconfig',
            name='grok_api_key',
            field=models.CharField(blank=True, help_text='Clave personal de API de Grok/xAI (opcional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='korvaaiconfig',
            name='monthly_token_limit',
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='korvaaiconfig',
            name='preferred_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('grok', 'Grok/xAI')], default='gemini', max_length=20),
        ),
        migrations.AddField(
            model_name='korvaaiconfig',
            name='seen_ai_tutorial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='korvaaiconfig',
            name='total_tokens_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
