# Generated by Django 6.0.5 on 2026-06-15 15:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('NIO', 'C$ Córdobas'), ('USD', '$ Dólares US')], default='NIO', max_length=3)),
                ('category', models.CharField(choices=[('ventas', 'Ventas'), ('compras', 'Compras')], max_length=20)),
                ('image', models.ImageField(upload_to='products/')),
                ('contact_whatsapp', models.CharField(help_text='Ej: +50587654321 o 87654321', max_length=20, validators=[django.core.validators.RegexValidator(message='Número de WhatsApp inválido', regex='^\\+?1?\\d{9,15}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
