# Generated by Django 6.0.5 on 2026-09-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ventas', 'Ventas'), ('compras', 'Compras'), ('servicios', 'Servicios')], max_length=20),
        ),
    ]
