# Generated by Django 6.0.5 on 2026-07-28 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_deal'),
        ('users', '0003_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('lafise', 'Lafise Bancentro'), ('banpro', 'Banpro Grupo Promerica'), ('bac', 'BAC Credomatic')], max_length=20)),
                ('account_type', models.CharField(choices=[('monetaria', 'Cuenta Monetaria'), ('ahorro', 'Cuenta de Ahorro')], default='monetaria', max_length=20)),
                ('account_number', models.CharField(max_length=30)),
                ('account_holder', models.CharField(max_length=200)),
                ('id_number', models.CharField(help_text='Cédula o RUC del titular', max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Teléfono registrado en el banco', max_length=15)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='users.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'En Proceso'), ('completed', 'Completado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.bankaccount')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='users.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total de la transaccion', max_digits=12)),
                ('currency', models.CharField(choices=[('NIO', 'C$ Córdobas'), ('USD', '$ Dólares US')], default='NIO', max_length=3)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Comision de Korva', max_digits=12)),
                ('seller_amount', models.DecimalField(decimal_places=2, help_text='Monto para el vendedor (total - comision)', max_digits=12)),
                ('reference', models.CharField(help_text='Referencia unica de pago', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Pago'), ('paid', 'Pagado (por confirmar)'), ('confirmed', 'Confirmado por el Vendedor'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('disputed', 'En Disputa')], default='pending', max_length=20)),
                ('bank', models.CharField(blank=True, choices=[('lafise', 'Lafise Bancentro'), ('banpro', 'Banpro Grupo Promerica'), ('bac', 'BAC Credomatic')], help_text='Banco usado para el pago', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('buyer_notes', models.TextField(blank=True, help_text='Notas del comprador al realizar el pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='users.profile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='marketplace.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='users.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
