# Generated by Django 6.0.5 on 2026-07-28 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_bankaccount_payoutrequest_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL de imagen externa (Google/Unsplash)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='contact_whatsapp',
            field=models.CharField(help_text='Ej: +50587654321', max_length=20, validators=[django.core.validators.RegexValidator(message='Número de WhatsApp inválido (ej: +50587654321)', regex='^\\+?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
