# Generated by Django 6.0.5 on 2026-08-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_product_contact_whatsapp_alter_product_image'),
        ('marketplace', '0006_product_image_url_alter_product_contact_whatsapp_and_more'),
    ]

    operations = [
    ]
