# Generated by Django 6.0.5 on 2026-06-15 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_posts', models.IntegerField(default=0)),
                ('total_products', models.IntegerField(default=0)),
                ('total_collaborations', models.IntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('followers_growth', models.IntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('last_generated', models.DateTimeField(auto_now=True)),
                ('period_month', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_report', to='users.profile')),
            ],
            options={
                'ordering': ['-last_generated'],
            },
        ),
    ]
