# Generated by Django 6.0.5 on 2026-06-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_image_message_video_alter_message_content'),
        ('users', '0002_emailverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read_status',
        ),
        migrations.AddField(
            model_name='message',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_messages', to='users.profile'),
        ),
    ]
