# Generated by Django 6.0.5 on 2026-06-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post_image_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='Video opcional para la publicación', null=True, upload_to='posts/videos/'),
        ),
    ]
