# Generated by Django 6.0.5 on 2026-06-22 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_messages', models.BooleanField(default=True)),
                ('email_likes', models.BooleanField(default=True)),
                ('email_comments', models.BooleanField(default=True)),
                ('email_follows', models.BooleanField(default=True)),
                ('email_product_inquiries', models.BooleanField(default=True)),
                ('email_mentions', models.BooleanField(default=True)),
                ('email_system', models.BooleanField(default=True)),
                ('push_messages', models.BooleanField(default=True)),
                ('push_likes', models.BooleanField(default=True)),
                ('push_comments', models.BooleanField(default=True)),
                ('push_follows', models.BooleanField(default=True)),
                ('push_product_inquiries', models.BooleanField(default=True)),
                ('push_mentions', models.BooleanField(default=True)),
                ('push_system', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('message', 'Nuevo Mensaje'), ('like', 'Like en tu publicación'), ('comment', 'Comentario en tu publicación'), ('follow', 'Nuevo seguidor'), ('product_inquiry', 'Consulta de producto'), ('mention', 'Mención'), ('system', 'Notificación del sistema')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx')],
            },
        ),
    ]
